server:
  port: 3344

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xu-weihao/cloud.git
          search-paths: config
          username: xu-weihao
          password: xwh950612
        default-label: main

eureka:
  instance:
    instance-id: config-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/